### ISSUE TITLE
RPC endpoint not listening by default

### ISSUE THREAD

**Issue by jaimeblasco** [decentraland/decentraland-node#13]
decentraland# ./bin/cli --apikey=$YOUR_RPC_APIKEY rpc dumpblockchain true | node scripts/list.js
Error: connect ECONNREFUSED 127.0.0.1:8332
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/decentraland/scripts/list.js:4:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)

**Comment by jaimeblasco** [comment]
What is the preferred way to configure the endpoint to start listening?

**Comment by jaimeblasco** [comment]
Nevermind, the problem is cli assumes the port is 8332 instead of 8301

**Comment by maraoz** [comment]
@jaimeblasco sorry about that, many people encounter this problem, we should fix it soon
