### ISSUE TITLE
Some webtorrent connections hang the node with EPIPE

### ISSUE THREAD

**Issue by eordano** [decentraland/decentraland-node#2]

**Comment by arhuaco** [comment]
I just got this. Same issue I guess. Program crashes.
```
[error] Connection timed out. (97.91.35.156:2301)
[debug] Refilling peers (7/8).
[debug] Connecting to 50.35.73.142:2301.
[debug] Received headers packet with 1 items (67.207.68.24:2301).
[debug] Received 1 headers from peer (67.207.68.24:2301).
[info] Added inbound peer (181.170.249.215:59778).
[debug] Ignoring leech: too many inbound (181.59.244.182).
[debug] Ignoring leech: too many inbound (46.101.15.62).
[debug] Ignoring leech: too many inbound (190.19.1.125).
[debug] Ignoring leech: too many inbound (138.197.44.64).
[debug] Peer has not responded to ping (159.203.87.161:57394).
[error] Connection timed out. (181.59.244.182:2301)
[error] Connection timed out. (190.19.1.125:2301)
[error] Connection timed out. (50.35.73.142:2301)
[debug] Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)
[error] write EPIPE

```

**Comment by martriay** [comment]
Not needed anymore as we moved to IPFS.
