### ISSUE TITLE
Memory Consumption Issue

### ISSUE THREAD

**Issue by thoragio** [decentraland/decentraland-node#20]
I'm seeing an issue with memory being consumed until there is apparently no available RAM left and then the node crashes.  To counter this I've written a script to restart the node again.

<img width="421" alt="screen shot 2017-03-18 at 15 29 00" src="https://cloud.githubusercontent.com/assets/9831905/24085562/d2a04dd2-0cfe-11e7-849b-d1a8157516b0.png">

The above was a node running with Docker.

I built a second node and ran it manually without Docker and have replicated the problem.

![screen shot 2017-03-19 at 23 42 03](https://cloud.githubusercontent.com/assets/9831905/24085578/f477a1e4-0cfe-11e7-9dae-9baca90568e6.png)

**Comment by maraoz** [comment]
Thanks for the report. How much RAM does that host have?

**Comment by thoragio** [comment]
2gb.

**Comment by thoragio** [comment]
Here's what's shown in the console right when it crashes:

```
[info] Connected to 67.207.68.24:2301.
[info] Connected to 46.101.15.62:2301.
[debug] Refilling peers (7/8).
[error] socket hangup (46.101.15.62:2301)
[error] socket hangup (67.207.68.24:2301)
[debug] Sending 4 addrs to peer (104.236.147.233:2301)
[debug] Requesting headers packet from peer with getheaders (104.236.147.233:2301).
[debug] Height: 9264, Hash: 0000009b322896191fa4aef161ffa00a4a14a2a05d1399c6b334cd9f1fbb65b6, Stop: null
[debug] Requesting headers packet from peer with getheaders (104.236.147.233:2302).
[debug] Height: 9264, Hash: 0000009b322896191fa4aef161ffa00a4a14a2a05d1399c6b334cd9f1fbb65b6, Stop: null
[debug] Sending 4 addrs to peer (104.236.147.233:2302)
[debug] Refilling peers (5/8).
[info] Received 4 addrs (hosts=5, peers=5) (104.236.147.233:2301).
[debug] Refilling peers (5/8).
[debug] Connecting to 46.101.15.62:2301.
[info] Connected to 46.101.15.62:2301.
[info] Received 4 addrs (hosts=6, peers=6) (104.236.147.233:2302).
[debug] Refilling peers (6/8).
[debug] Received headers packet with 1 items (104.236.147.233:2301).
[debug] Received 1 headers from peer (104.236.147.233:2301).
[error] socket hangup (46.101.15.62:2301)
[debug] Received headers packet with 1 items (104.236.147.233:2302).
[debug] Received 1 headers from peer (104.236.147.233:2302).
[debug] Received headers packet with 1 items (104.236.147.233:2301).
[debug] Received 1 headers from peer (104.236.147.233:2301).
[debug] Requesting 1/1 blocks from peer with getdata (104.236.147.233:2301).
[debug] Received headers packet with 1 items (104.236.147.233:2302).
[debug] Received 1 headers from peer (104.236.147.233:2302).
[debug] Received headers packet with 1 items (138.197.44.64:2301).
[debug] Received 1 headers from peer (138.197.44.64:2301).
[debug] Received headers packet with 1 items (159.203.87.161:2301).
[debug] Received 1 headers from peer (159.203.87.161:2301).
[debug] Received headers packet with 1 items (128.199.43.55:2301).
[debug] Received 1 headers from peer (128.199.43.55:2301).
[debug] Memory: rss=116mb, js-heap=56/72mb native-heap=44mb
[info] Block 000000421ce93cea321337895ce177d8ad4ccf0bbe6bd860203723620e924341 (9266) added to chain (size=254 txs=1 time=18.667898).
[debug] Coin Cache: size=0mb, items=36.
[info] Miner: hashrate=249khs hashes=37223043 target=492662854 height=9260 best=000000fe23b1eaf59096e4de5fc4e7b3f17c968e942f515a86c7efeed39c64a2
[debug] Refilling peers (5/8).
[debug] Refilling peers (5/8).
[debug] Refilling peers (5/8).
[debug] Error: write EPIPE
    at exports._errnoException (util.js:1033:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:816:14)
[error] write EPIPE
internal/process.js:188
      throw errnoException(err, 'kill');
      ^

Error: kill ESRCH
    at exports._errnoException (util.js:1033:11)
    at process.kill (internal/process.js:188:13)
    at process.<anonymous> (/home/thoragio/bronzeage-node/node_modules/electron-eval/lib/index.js:152:19)
    at emitOne (events.js:101:20)
    at process.emit (events.js:191:7)
    at process.exit (internal/process.js:162:15)
    at process.<anonymous> (/home/thoragio/bronzeage-node/bin/node:35:11)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:299:26)
```

**Comment by thoragio** [comment]
I'm closing this one now. Forgot to do it earlier when the problem was sorted by some changes pushed awhile back by @eordano.
