### ISSUE TITLE
Can't get it to run after installing.

### ISSUE THREAD

**Issue by finnbear** [decentraland/decentraland-node#21]
I followed the non-docker installation instructions on my Ubuntu 16.04 server.

This command: `./bin/start` produces the error:
```
/home/xxxxxxx/decentraland/bronzeage-node/lib/blockchain/chain.js:184
  const { tiles } = yield this._bfs();
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/minecraft/decentraland/bronzeage-node/lib/node/fullnode.js:15:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

```

**Comment by illustris** [comment]
You have an older version of nodejs. Install version 6.10.2 or newer from [here](https://nodejs.org/en/)

**Comment by maraoz** [comment]
Thanks @illustris for answering!
