### ISSUE TITLE
Bronze Age node doesn't start on windows

### ISSUE THREAD

**Issue by dospunk** [decentraland/decentraland-node#22]
Running bin/start produces this error

    ./bin/decentraland-node --fast --port=2301 --prefix="/data" --httpport=8301 --n=testnet --apikey=$NODE_API_KEY --contentport=9301 --startminer
    ^
    SyntaxError: Unexpected token .
        at Object.exports.runInThisContext (vm.js:76:16)
        at Module._compile (module.js:513:28)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)
        at Function.Module._load (module.js:409:3)
        at Module.runMain (module.js:575:10)
        at run (bootstrap_node.js:352:7)
        at startup (bootstrap_node.js:144:9)
        at bootstrap_node.js:467:3`

**Comment by dospunk** [comment]
Whelp, I am I fool and didn't realize that they were bash files. My bad
