### ISSUE TITLE
How do I know if I've mined land?

### ISSUE THREAD

**Issue by QuibblingAsh42** [decentraland/decentraland-node#23]
Just learned about the project last night, and very excited to start playing around with it!  I fired up a node last night, and let it ran.  I had the memory exhaustion issue others have mentioned, but I'm not seeing a way to determine if I've successfully mined any new land or not.  How do I find that out?

To that point, I think this project would get a bit more following if there were some more complete documentation.  I'd be happy to work with you guys to help out getting that done.

**Comment by nickmomrik** [comment]
I'm having trouble figuring this out as well. I'm running a node on a Raspberry Pi 3B. I've tried to follow the docs from bcoin, like https://github.com/bcoin-org/bcoin/wiki/Beginner's-Guide, but there seems to be a lot more differences than the README here mentions.

**Comment by HPrivakos** [comment]
You can use the cli with this command:

./bin/cli --apikey=$YOUR_RPC_APIKEY rpc dumpblockchain true | node scripts/list.js

**Comment by nickmomrik** [comment]
Each time I start the node (mine seems to be crashing a lot too) it uses a different API key. Is there a log of all of those API keys somewhere that need to be checked for mined tiles?

When I use one of them with that command I get
```
Error: connect ECONNREFUSED 127.0.0.1:8332
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
undefined:1
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
```

Figured out I can run
`sudo ./bin/cli --apikey=$YOUR_RPC_APIKEY --url=http://0.0.0.0:8301 rpc dumpblockchain true | node scripts/list.js`
with an API key but then it times out...

```
Error: Request timed out.
    at Timeout.<anonymous> (/home/pi/bronzeage-node/lib/http/request.js:295:17)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
undefined:1
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
```

**Comment by qst0** [comment]
Having these same issues.

**Comment by arunesh90** [comment]
![image](https://cloud.githubusercontent.com/assets/5787588/25583298/82a8638c-2e91-11e7-9ba0-4423b385f4b9.png)
@nickmomrik @qst0

**Comment by HPrivakos** [comment]
You will get the "socket hang out" error if your pc is really tooooo slow, but in this case, we need to add a ping for keep the socket open

**Comment by masonjeffers** [comment]
The above worked for me! Thanks.

**Comment by Dmitry1987** [comment]
Hi guys,
it's a curious project, but all links to Slack channel are broken, is there an active chat at the moment?

**Comment by Dmitry1987** [comment]
The documentation and good illustrated guides are missing. The project is like in its super-micro-infancy stage :) .  I'm good with Electron and Vue.js, is there anything "desktop GUI\Web-UI" related I can help with?  like land explorer or kind of "wallet"?

**Comment by Dmitry1987** [comment]
The script to list tiles works, thanks @HPrivakos . But what are all zeroes mean in each tile?
```
Controlled tiles:
0 -1 '00000000000000000000000000000000000000000000000000000000000000000000'
2 0 '00000000000000000000000000000000000000000000000000000000000000000000'
1 -1 '00000000000000000000000000000000000000000000000000000000000000000000'
2 -1 '00000000000000000000000000000000000000000000000000000000000000000000'
3 0 '00000000000000000000000000000000000000000000000000000000000000000000'
3 -1 '00000000000000000000000000000000000000000000000000000000000000000000'
4 -1 '00000000000000000000000000000000000000000000000000000000000000000000'
5 -1 '00000000000000000000000000000000000000000000000000000000000000000000'
4 -2 '00000000000000000000000000000000000000000000000000000000000000000000'
5 -2 '00000000000000000000000000000000000000000000000000000000000000000000'
4 -3 '00000000000000000000000000000000000000000000000000000000000000000000'
5 -3 '00000000000000000000000000000000000000000000000000000000000000000000'
4 -4 '00000000000000000000000000000000000000000000000000000000000000000000'
6 -3 '00000000000000000000000000000000000000000000000000000000000000000000'
5 -4 '00000000000000000000000000000000000000000000000000000000000000000000'
4 -5 '00000000000000000000000000000000000000000000000000000000000000000000'
5 -5 '00000000000000000000000000000000000000000000000000000000000000000000'
4 -6 '00000000000000000000000000000000000000000000000000000000000000000000'
5 -6 '00000000000000000000000000000000000000000000000000000000000000000000'
19
```

My API KEY is the private key to those, or a public key actually?  sorry for being a crypto noob :P

**Comment by Dmitry1987** [comment]
Coordinates look like center of the universe :D , this node is mining and creating tiles on my 'private' blockchain somewhere locally, or on the real distributed one?  I expected it to run few days before it finds some block
