### ISSUE TITLE
Cannot upload on negative tiles

### ISSUE THREAD

**Issue by HPrivakos** [decentraland/decentraland-node#24]
Hey,
I can't upload anything on a tile with negative coordiates or get informations about it:

./bin/cli --apikey=abc rpc gettile -118 -84
Return Null

Result on the node:
```
[debug] Handling RPC call : gettile.
[debug] []
[error] gettile "x", "y"
```

----

./bin/cli --apikey=abc rpc settile -118 -84 test64
Return:
```
Reading tile file undefined
Error: File undefined not found
    at CLI.rpc (/home/hprivakos/bronzeage-node/bin/cli:485:13)
    at rpc.next (<anonymous>)
    at step (/home/hprivakos/bronzeage-node/lib/utils/co.js:31:22)
    at /home/hprivakos/bronzeage-node/lib/utils/co.js:64:5
    at exec (/home/hprivakos/bronzeage-node/lib/utils/co.js:21:10)
    at CLI.rpc (/home/hprivakos/bronzeage-node/lib/utils/co.js:92:12)
    at CLI.handleNode (/home/hprivakos/bronzeage-node/bin/cli:657:25)
    at handleNode.next (<anonymous>)
    at step (/home/hprivakos/bronzeage-node/lib/utils/co.js:31:22)
    at /home/hprivakos/bronzeage-node/lib/utils/co.js:64:5
```

---

I have no problem while using the same command but with positive coordinates

**Comment by HPrivakos** [comment]
Resolved by #25
