### ISSUE TITLE
[error] Number exceeds 2^53-1

### ISSUE THREAD

**Issue by Alonzo-Coeus** [decentraland/decentraland-node#26]
when i start the node i get this error if is start it up with mining args only

```    at Object._read64 (C:\Users\Dougal\bronzeage-node\lib\utils\encoding.js:153:
5)
    at Object.read64 (C:\Users\Dougal\bronzeage-node\lib\utils\encoding.js:175:1
9)
    at BufferReader.read64 (C:\Users\Dougal\bronzeage-node\lib\utils\reader.js:3
32:18)
    at Output.fromReader (C:\Users\Dougal\bronzeage-node\lib\primitives\output.j
s:259:15)
    at Function.fromReader (C:\Users\Dougal\bronzeage-node\lib\primitives\output
.js:282:23)
    at TX.fromReader (C:\Users\Dougal\bronzeage-node\lib\primitives\tx.js:2158:3
0)
    at Function.fromReader (C:\Users\Dougal\bronzeage-node\lib\primitives\tx.js:
2121:19)
    at Block.fromReader (C:\Users\Dougal\bronzeage-node\lib\primitives\block.js:
753:13)
    at Block.fromRaw (C:\Users\Dougal\bronzeage-node\lib\primitives\block.js:774
:15)
    at Function.fromRaw (C:\Users\Dougal\bronzeage-node\lib\primitives\block.js:
798:22)
[error] Number exceeds 2^53-1
```

anyone know what is wrong.
is it do do with this?
```
[debug] Error: electron-eval error: Electron process exited with cod
Stderr:
'"C:\Users\Dougal\bronzeage-node\node_modules\electron\dist\electron
cognized as an internal or external command,
operable program or batch file.

    at ChildProcess.<anonymous> (C:\Users\Dougal\bronzeage-node\node
ctron-eval\lib\index.js:174:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.cp.emit (C:\Users\Dougal\bronzeage-node\node_mod
pawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
[error] electron-eval error: Electron process exited with code 1.
```

**Comment by eordano** [comment]
What happens if you try running the `bin/start` script instead of directly running the `bin/node` one?
