### ISSUE TITLE
STUPID errror chains.js help me please.

### ISSUE THREAD

**Issue by kylerchin** [decentraland/decentraland-node#29]
```root@Sandy-Lenovo-ideapad-FLEX-4-1470:/home/sandy/bronzeage-node# ./bin/start
/home/sandy/bronzeage-node/lib/blockchain/chain.js:184
  const { tiles } = yield this._bfs();
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/sandy/bronzeage-node/lib/node/fullnode.js:15:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)```
anyone know how to fix?

**Comment by HPrivakos** [comment]
Update your nodejs

**Comment by kylerchin** [comment]
Thanks! NodeJS is stupid with versions.

**Comment by eordano** [comment]
Updated package.json to show that it needs a later version of node :)
