### ISSUE TITLE
leveldown is not a dependency

### ISSUE THREAD

**Issue by arhuaco** [decentraland/decentraland-node#5]
I needed to install it by hand. I was running outside the docker image.

**Comment by arhuaco** [comment]
Mmm. I see it there. In general, something happened to me in a second install. The program complained about the bn module not being installed and it's listed in the packages.json.

I am new to node and I wonder if this happens often (flaky installs).

**Comment by arhuaco** [comment]
So, I did another install and the same thing happened. I am using Ubuntu 16.04.

```
$ npm install
```
All installed now.. ?!

```
ME@decent:~/git/bronzeage-node$ bin/start
/home/ME/git/bronzeage-node/lib/db/backends.js:17
    throw new Error('Database backend "' + name + '" not found.');
    ^

Error: Database backend "leveldown" not found.
    at Object.get (/home/ME/git/bronzeage-node/lib/db/backends.js:17:11)
    at Function.getTarget (/home/ME/git/bronzeage-node/lib/db/ldb.js:121:21)
    at LDB (/home/ME/git/bronzeage-node/lib/db/ldb.js:32:20)
```

Dependency not found. Let's install again.

```
ME@decent:~/git/bronzeage-node$ npm install leveldown

> leveldown@1.5.0 install /home/ME/git/bronzeage-node/node_modules/leveldown
> prebuild --install
```

(After this the program starts)
