### ISSUE TITLE
Repeated WebTorrent verification failures

### ISSUE THREAD

**Issue by ghost** [decentraland/decentraland-node#58]
My node shows a repeated error: `WebTorrent Error: Piece 0 failed verification`. It's very frequent, maybe several times per second.

The node runs Ubuntu Server 17.04.

Pasting a sequence of them here:

```
[info] XXX just downloaded: 690
[info] XXX total downloaded: 690
[info] XXX download speed: 1794
[info] XXX progress: 1
[warning] WebTorrent Error: Piece 0 failed verification
    at /home/berry/sft/land-bronze/bronzeage-node/node_modules/webtorrent/lib/torrent.js:1554:30
    at /home/berry/sft/land-bronze/bronzeage-node/node_modules/simple-sha1/index.js:6:5
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
[info] XXX just downloaded: 690
[info] XXX total downloaded: 690
[info] XXX download speed: 1794
[info] XXX progress: 1
[warning] WebTorrent Error: Piece 0 failed verification
    at /home/berry/sft/land-bronze/bronzeage-node/node_modules/webtorrent/lib/torrent.js:1554:30
    at /home/berry/sft/land-bronze/bronzeage-node/node_modules/simple-sha1/index.js:6:5
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
[info] XXX just downloaded: 690
[info] XXX total downloaded: 690
[info] XXX download speed: 1794
[info] XXX progress: 1
[warning] WebTorrent Error: Piece 0 failed verification
    at /home/berry/sft/land-bronze/bronzeage-node/node_modules/webtorrent/lib/torrent.js:1554:30
    at /home/berry/sft/land-bronze/bronzeage-node/node_modules/simple-sha1/index.js:6:5
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
[info] XXX just downloaded: 690
[info] XXX total downloaded: 690
[info] XXX download speed: 1932
[info] XXX progress: 1
[warning] WebTorrent Error: Piece 0 failed verification
    at /home/berry/sft/land-bronze/bronzeage-node/node_modules/webtorrent/lib/torrent.js:1554:30
    at /home/berry/sft/land-bronze/bronzeage-node/node_modules/simple-sha1/index.js:6:5
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
[info] XXX just downloaded: 690
[info] XXX total downloaded: 690
[info] XXX download speed: 1794
[info] XXX progress: 1
[warning] WebTorrent Error: Piece 0 failed verification
    at /home/berry/sft/land-bronze/bronzeage-node/node_modules/webtorrent/lib/torrent.js:1554:30
    at /home/berry/sft/land-bronze/bronzeage-node/node_modules/simple-sha1/index.js:6:5
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
[info] XXX just downloaded: 690
[info] XXX total downloaded: 690
[info] XXX download speed: 1932
[info] XXX progress: 1
[warning] WebTorrent Error: Piece 0 failed verification
    at /home/berry/sft/land-bronze/bronzeage-node/node_modules/webtorrent/lib/torrent.js:1554:30
    at /home/berry/sft/land-bronze/bronzeage-node/node_modules/simple-sha1/index.js:6:5
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
[info] XXX just downloaded: 690
[info] XXX total downloaded: 690
[info] XXX download speed: 1794
[info] XXX progress: 1
[warning] WebTorrent Error: Piece 0 failed verification
    at /home/berry/sft/land-bronze/bronzeage-node/node_modules/webtorrent/lib/torrent.js:1554:30
    at /home/berry/sft/land-bronze/bronzeage-node/node_modules/simple-sha1/index.js:6:5
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

**Comment by ghost** [comment]
Seems to have stopped after a while. Maybe it's a temporary thing early in a new chain sync.

**Comment by martriay** [comment]
Not needed anymore as we moved to IPFS.
