### ISSUE TITLE
bronzeage-node crashes with "Electron process exited with code 2"

### ISSUE THREAD

**Issue by arhuaco** [decentraland/decentraland-node#7]
At commit d82aafb6ee0a069c55df6edceeea5a1eec7fe8e6 .
Ubuntu 16.64. Crash log:

[info] Received version (181.170.249.215:57364): version=70014 height=2793 services=111 agent=/decentraland:1.0.0-alpha/
[debug] Added time data: samples=29, offset=-3 (0 minutes).
[info] Time offset: -22 (0 minutes).
[info] Received 1 addrs (hosts=6, peers=14) (181.170.249.215:57364).
[debug] Refilling peers (6/8).
[debug] Connecting to 181.170.249.215:2301.
[debug] Error: electron-eval error: Electron process exited with code 2.
Stderr:
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[30449:0315/153313.927959:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:55522 (eth0)
[30449:0315/153313.961470:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:55522 (eth0)
[30449:0315/153313.988653:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:51177 (eth0)
[30449:0315/153313.988923:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:51177 (eth0)
[30449:0315/153314.019876:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:56279 (eth0)
[30449:0315/153314.020160:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:56279 (eth0)
[30449:0315/153314.036528:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:55375 (eth0)
[30449:0315/153314.036654:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:55375 (eth0)
[30449:0315/153314.058647:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:46544 (eth0)
[30449:0315/153314.063498:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:46544 (eth0)
[30449:0315/153314.107081:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:50564 (eth0)
[30449:0315/153314.108782:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:50564 (eth0)
[30449:0315/153314.130778:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:51046 (eth0)
[30449:0315/153314.132695:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:51046 (eth0)
(more like this...)
[30449:0315/153529.970814:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:41323 (eth0)
    at ChildProcess.<anonymous> (/home/len/git/bronzeage-node/node_modules/electron-eval/lib/index.js:174:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
[error] electron-eval error: Electron process exited with code 2.
Stderr:
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[30449:0315/153313.927959:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:55522 (eth0)
[30449:0315/153313.988653:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:51177 (eth0)
[30449:0315/153313.988923:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:51177 (eth0)
[30449:0315/153314.019876:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:56279 (eth0)
[30449:0315/153314.020160:ERROR:stunport.cc(89)] Binding request timed out from 10.46.0.x:56279 (eth0)
(more like this and the program dies)

**Comment by maraoz** [comment]
Thanks for reporting! we'll look into this

**Comment by eordano** [comment]
Hey @arhuaco, can you please try to run

    sudo apt-get install -y --no-install-recommends xvfb libgtk2.0-0 libxtst-dev libxss-dev libgconf2-dev libnss3 libasound2-dev

Please let me know if this is resolves the issue and I'll add that to the instructions

**Comment by arhuaco** [comment]
@eordano As we chatted yesterday, the problem seems to be because I'm using just 1GB of RAM. I'll have to use a bigger node.

**Comment by arhuaco** [comment]
I had the packages installed already (I took them from the Docker recipe).

**Comment by arhuaco** [comment]
I'll upgrade the node now. If there are no more crashes then we can confirm that the issue is OOM.

**Comment by arhuaco** [comment]
This was most likely OOM. I haven't seen it again since I moved up from 1G.
