### ISSUE TITLE
Verification Failure

### ISSUE THREAD

**Issue by victorstewart** [decentraland/decentraland-node#77]
Keep getting these errors... and the miner itself never seems to start?

```
[error] Verification failure: duplicate (code=duplicate, score=0, hash=0000007b4598c9d26b0cc65b9e225db84cc2645538ab6fb53441c1c597387b71)
{ Error: Verification failure: duplicate (code=duplicate, score=0, hash=0000007b4598c9d26b0cc65b9e225db84cc2645538ab6fb53441c1c597387b71)
    at Chain.add (/root/decentraland/bronzeage-node/lib/blockchain/chain.js:1297:13)
    at next (native)
    at step (/root/decentraland/bronzeage-node/lib/utils/co.js:31:22)
    at succeed (/root/decentraland/bronzeage-node/lib/utils/co.js:57:7)
  type: 'VerifyError',
  hash: <Buffer 71 7b 38 97 c5 c1 41 34 b5 6f ab 38 55 64 c2 4c b8 5d 22 9e 5b c6 0c 6b d2 c9 98 45 7b 00 00 00>,
  malleated: false,
  code: 'duplicate',
  reason: 'duplicate',
  score: 0,
  message: 'Verification failure: duplicate (code=duplicate, score=0, hash=0000007b4598c9d26b0cc65b9e225db84cc2645538ab6fb53441c1c597387b71)' }
```

Just needing a never ending feed of this..

```
[info] Received 1 addrs (hosts=137, peers=8) (138.197.78.162:2301).
[info] Received 136 addrs (hosts=137, peers=8) (138.197.78.162:2301).
[info] Removed loader peer (138.197.103.55:2301).
[info] Setting loader peer (138.197.103.55:2301).
[info] Connected to 138.197.103.55:2301.
[info] Received version (138.197.103.55:2301): version=70014 height=25645 services=111 agent=/decentraland:1.0.0-alpha/
[info] Received 1 addrs (hosts=137, peers=7) (138.197.103.55:2301).
[info] Connected to 138.197.44.64:2301.
[info] Received version (138.197.44.64:2301): version=70014 height=25645 services=111 agent=/decentraland:1.0.0-alpha/
[info] Received 136 addrs (hosts=137, peers=8) (138.197.103.55:2301).
[info] Received 1 addrs (hosts=137, peers=8) (138.197.44.64:2301).
[info] Received 136 addrs (hosts=137, peers=8) (138.197.44.64:2301).
[info] Block 00000012828ba24cbabdf3165560208a4bcbdacd5ac857a0dea581992b6224d4 (25646) added to chain (size=254 txs=1 time=3.517175).
```

**Comment by ghost** [comment]
Hi victor. These verification failures should be OK, the node will encounter lots of issues in normal operation. It's designed to keep running whenever possible. As long as the output keeps scrolling it's OK.

About the miner, noticed recently that the start script doesn't start it correctly. If you open `localhost:5000` in your browser you should get the web interface to your node. There you can flip the miner on.

**Comment by victorstewart** [comment]
oh thanks! I'm running it on headless servers via terminal... i tried using a text-based browser but the Miner portion of the page just reads "Loading...". Any way to do this in the start script?

**Comment by ghost** [comment]
Yes, it's in `bin/start`. The line that broke is this one:

`  --startminer=$START_MINER`

It's defaulting to `yes`, but it seems this option doesn't work with a value. So if you take out the value then the miner starts:

`  --startminer`

**Comment by victorstewart** [comment]
awesome it's working now, thanks! someone should make a note of that on the README

**Comment by ghost** [comment]
You got it friend.
