### ISSUE TITLE
Error: Bad auth.

### ISSUE THREAD

**Issue by beatnu69** [decentraland/decentraland-node#85]
My apikey shows up when mining... however when i go to http://localhost:5000 everything is loading. Please help!
 ./bin/cli --apikey=myApiKey rpc dumpblockchain true | node scripts/list.js
Error: Bad auth.
    at RPCClient.call (/Users/mac/bronzeage-node/lib/http/rpcclient.js:75:13)
    at call.next (<anonymous>)
    at step (/Users/mac/bronzeage-node/lib/utils/co.js:31:22)
    at succeed (/Users/mac/bronzeage-node/lib/utils/co.js:57:7)
    at process._tickCallback (internal/process/next_tick.js:103:7)
(node:32417) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected end of JSON input
(node:32417) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by beatnu69** [comment]
I no longer get the unhandled promise rejection just this:

./bin/cli --apikey=********ApiKey rpc dumpblockchain true > tiles.json
Error: Bad auth.
    at RPCClient.call (/Users/mac/bronzeage-node/lib/http/rpcclient.js:75:13)
    at call.next (<anonymous>)
    at step (/Users/mac/bronzeage-node/lib/utils/co.js:31:22)
    at succeed (/Users/mac/bronzeage-node/lib/utils/co.js:57:7)
    at process._tickCallback (internal/process/next_tick.js:103:7)
